name = "Hydration"
uuid = "34dc154a-538c-46a5-bd37-00ae0192372e"
authors = ["Frames White <me@oxinabox.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
